[tool.poetry]
name = "PicImageSearch"
version = "3.3.2"
description = "PicImageSearch APIs for Python 3.x 适用于 Python 3 以图搜源整合API"
authors = ["kitUIN <kulujun@gmail.com>"]
maintainers = ["kitUIN <kulujun@gmail.com>", "lleans", "chinoll", "NekoAria"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "PicImageSearch" }
]
homepage = "https://github.com/kitUIN/PicImageSearch"
repository = "https://github.com/kitUIN/PicImageSearch"
keywords = ["google", "iqdb", "saucenao", "tracemoe", "ascii2d"]

[tool.poetry.dependencies]
python = "^3.6"
httpx = "^0.22.0"
lxml = "^4.8.0"
pyquery = "^1.4.3"

[tool.poetry.dev-dependencies]
loguru = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
